name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  env-file: variables.env  
jobs:
  read_values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "get_variables"
        run: echo "Luka"
  build_app:
    runs-on: ubuntu-latest
    needs: read_values
    steps:
      - uses: actions/checkout@v3
      - name: "docker_build"
        run: |
          docker build . -t primeiro-build:v1
          docker images
  scan_security:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - uses: actions/checkout@v3
      - name: "security_pipe"
        run: echo "Luka"
  create_artifactory:
    runs-on: ubuntu-latest
    needs: scan_security
    steps:
      - uses: actions/checkout@v3
      - name: "zip_archives"
        run: echo "Luka"