name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  read_values:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
        name: "get_variables"
        env-file: variables.env 
        run: echo "Luka"
  build_app:
    runs-on: ubuntu-latest
    needs: read_values
    steps:
      - 
        uses: actions/checkout@v3
        name: "docker_build"
        run: |
          docker build . -t primeiro-build:v1
          docker images
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.lukapagliarini }}
          password: ${{ secrets.bb85220f-bcac-4020-9cad-2ccb71ab2479 }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:buildcache,mode=max
  scan_security:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - 
        uses: actions/checkout@v3
        name: "security_pipe"
        run: echo "Luka"
  create_artifactory:
    runs-on: ubuntu-latest
    needs: scan_security
    steps:
      - 
        uses: actions/checkout@v3
        name: "zip_archives"
        run: echo "Luka"